2021-03-28 03:01:51,131 DEBUG asyncio Using selector: EpollSelector
2021-03-28 03:01:55,938 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4987) discovered
2021-03-28 03:01:55,941 DEBUG quic [0000000000000001] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-03-28 03:01:55,955 DEBUG quic [0000000000000001] TLS State.SERVER_EXPECT_CLIENT_HELLO -> State.SERVER_EXPECT_FINISHED
2021-03-28 03:01:56,442 DEBUG quic [0000000000000001] Discarding epoch Epoch.INITIAL
2021-03-28 03:01:56,444 DEBUG quic [0000000000000001] TLS State.SERVER_EXPECT_FINISHED -> State.SERVER_POST_HANDSHAKE
2021-03-28 03:01:56,444 DEBUG quic [0000000000000001] Discarding epoch Epoch.HANDSHAKE
2021-03-28 03:01:56,444 INFO quic [0000000000000001] ALPN negotiated protocol hq-29
2021-03-28 03:01:56,445 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4987) validated by handshake
2021-03-28 03:01:56,910 DEBUG quic [eb41351317aabdb5] Network path ('127.0.0.1', 4987) discovered
2021-03-28 03:01:56,912 DEBUG quic [eb41351317aabdb5] Payload decryption failed
2021-03-28 03:01:57,103 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-03-28 03:01:57,413 DEBUG quic [eb41351317aabdb5] Network path ('127.0.0.1', 4988) discovered
2021-03-28 03:01:57,413 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-03-28 03:01:57,686 DEBUG quic [0000000000000001] Loss detection triggered
2021-03-28 03:01:57,686 DEBUG quic [0000000000000001] Sending PING (probe) in packet 4
2021-03-28 03:01:58,690 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4988) discovered
2021-03-28 03:01:58,691 DEBUG quic [0000000000000001] Stream 28 created by peer
2021-03-28 03:01:58,691 DEBUG quic [0000000000000001] Stream 32 created by peer
2021-03-28 03:01:58,691 DEBUG quic [0000000000000001] Received PING (probe) response
2021-03-28 03:01:58,692 DEBUG quic [0000000000000001] Stream 16 created by peer
2021-03-28 03:01:58,692 DEBUG quic [0000000000000001] Stream 36 created by peer
2021-03-28 03:01:58,692 DEBUG quic [0000000000000001] Peer switching to CID eb41351317aabdb5 (1)
2021-03-28 03:01:58,692 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4988) promoted
2021-03-28 03:01:58,693 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:01:58,693 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:01:58,693 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:01:58,694 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:01:59,199 DEBUG quic [0000000000000001] Network path ('127.0.0.1', 4988) validated by challenge
2021-03-28 03:01:59,199 DEBUG quic [0000000000000001] Stream 4 created by peer
2021-03-28 03:01:59,200 DEBUG quic [0000000000000001] Stream 40 created by peer
2021-03-28 03:01:59,200 DEBUG quic [0000000000000001] Peer switching to CID 9c8cce61c835acf5 (0)
2021-03-28 03:01:59,200 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:01:59,200 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:00,299 DEBUG quic [0000000000000001] Stream 48 created by peer
2021-03-28 03:02:00,299 DEBUG quic [0000000000000001] Stream 12 created by peer
2021-03-28 03:02:00,300 DEBUG quic [0000000000000001] Stream 44 created by peer
2021-03-28 03:02:00,300 DEBUG quic [0000000000000001] Peer switching to CID eb41351317aabdb5 (1)
2021-03-28 03:02:00,300 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:00,301 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:00,301 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:01,504 DEBUG quic [0000000000000001] Stream 52 created by peer
2021-03-28 03:02:01,504 DEBUG quic [0000000000000001] Stream 56 created by peer
2021-03-28 03:02:01,505 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:01,505 INFO quic [0000000000000001] HTTP request GET /index.html
2021-03-28 03:02:01,852 DEBUG quic [0000000000000001] Loss detection triggered
2021-03-28 03:02:01,925 DEBUG quic [0000000000000001] Peer switching to CID 9c8cce61c835acf5 (0)
2021-03-28 03:02:02,919 DEBUG quic [0000000000000001] Stream 20 created by peer
2021-03-28 03:02:02,920 DEBUG quic [0000000000000001] Peer switching to CID eb41351317aabdb5 (1)
2021-03-28 03:02:02,920 INFO quic [0000000000000001] HTTP request GET /index.html
