2021-06-02 11:37:27,651 DEBUG asyncio Using selector: EpollSelector
2021-06-02 11:37:27,656 DEBUG quic [8d096c659fd9135e] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-06-02 11:37:28,113 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:28,158 DEBUG quic [8d096c659fd9135e] Loss detection triggered
2021-06-02 11:37:28,246 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:28,508 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:28,859 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:29,162 DEBUG quic [8d096c659fd9135e] Loss detection triggered
2021-06-02 11:37:29,495 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:29,775 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:30,124 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:30,608 DEBUG quic [8d096c659fd9135e] Decryption key is not available
2021-06-02 11:37:30,809 DEBUG quic [8d096c659fd9135e] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-06-02 11:37:30,810 DEBUG quic [8d096c659fd9135e] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-06-02 11:37:31,164 DEBUG quic [8d096c659fd9135e] Loss detection triggered
2021-06-02 11:37:31,184 WARNING quic [8d096c659fd9135e] Error: 10, reason: Unexpected frame type, frame_type: 30
2021-06-02 11:37:31,184 DEBUG quic [8d096c659fd9135e] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
2021-06-02 11:37:32,685 DEBUG quic [8d096c659fd9135e] Discarding epoch Epoch.INITIAL
2021-06-02 11:37:32,685 DEBUG quic [8d096c659fd9135e] Discarding epoch Epoch.HANDSHAKE
2021-06-02 11:37:32,686 DEBUG quic [8d096c659fd9135e] Discarding epoch Epoch.ONE_RTT
2021-06-02 11:37:32,686 DEBUG quic [8d096c659fd9135e] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "examples/http3_client.py", line 465, in <module>
    zero_rtt=args.zero_rtt,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 313, in run
    wait_connected=not zero_rtt,
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/compat.py", line 17, in __aenter__
    return await self.gen.__anext__()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/client.py", line 89, in connect
    await protocol.wait_connected()
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
