2021-05-28 03:34:12,529 DEBUG asyncio Using selector: EpollSelector
2021-05-28 03:34:12,534 DEBUG quic [548db2080131739f] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-05-28 03:34:12,814 DEBUG quic [548db2080131739f] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-05-28 03:34:12,815 DEBUG quic [548db2080131739f] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-05-28 03:34:12,943 DEBUG quic [548db2080131739f] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2021-05-28 03:34:12,943 DEBUG quic [548db2080131739f] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2021-05-28 03:34:12,944 DEBUG quic [548db2080131739f] TLS State.CLIENT_EXPECT_CERTIFICATE_VERIFY -> State.CLIENT_EXPECT_FINISHED
2021-05-28 03:34:12,945 DEBUG quic [548db2080131739f] TLS State.CLIENT_EXPECT_FINISHED -> State.CLIENT_POST_HANDSHAKE
2021-05-28 03:34:12,945 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/quic/connection.py", line 923, in receive_datagram
    context, plain_payload
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/quic/connection.py", line 2058, in _payload_received
    frame_handler(context, frame_type, buf)
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/quic/connection.py", line 1420, in _handle_crypto_frame
    self._parse_transport_parameters(ext_data)
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/quic/connection.py", line 2109, in _parse_transport_parameters
    quic_transport_parameters = pull_quic_transport_parameters(Buffer(data=data))
  File "/home/chris/TVOQE_UPGRADE_27/quic/aioquic/src/aioquic/quic/packet.py", line 362, in pull_quic_transport_parameters
    assert buf.tell() == param_start + param_len
AssertionError
2021-05-28 03:34:13,036 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:13,037 DEBUG quic [548db2080131739f] Discarding epoch Epoch.INITIAL
2021-05-28 03:34:13,079 DEBUG quic [548db2080131739f] Discarding epoch Epoch.HANDSHAKE
2021-05-28 03:34:14,036 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:14,037 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 4
2021-05-28 03:34:14,550 DEBUG quic [548db2080131739f] Received PING (probe) response
2021-05-28 03:34:15,602 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:15,602 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 5
2021-05-28 03:34:16,291 DEBUG quic [548db2080131739f] Received PING (probe) response
2021-05-28 03:34:17,108 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:17,108 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 6
2021-05-28 03:34:17,972 DEBUG quic [548db2080131739f] Received PING (probe) response
2021-05-28 03:34:18,769 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:18,769 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 7
2021-05-28 03:34:20,933 DEBUG quic [548db2080131739f] Received PING (probe) response
2021-05-28 03:34:22,013 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:22,014 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 8
2021-05-28 03:34:24,014 DEBUG quic [548db2080131739f] Received PING (probe) response
2021-05-28 03:34:26,287 DEBUG quic [548db2080131739f] Loss detection triggered
2021-05-28 03:34:26,287 DEBUG quic [548db2080131739f] Sending PING (probe) in packet 9
2021-05-28 03:34:28,370 DEBUG quic [548db2080131739f] Received PING (probe) response
