2021-04-29 18:28:04,737 DEBUG asyncio Using selector: EpollSelector
2021-04-29 18:28:09,695 DEBUG quic [0000000000000002] Network path ('127.0.0.1', 4987) discovered
2021-04-29 18:28:09,699 DEBUG quic [0000000000000002] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-04-29 18:28:09,713 DEBUG quic [0000000000000002] TLS State.SERVER_EXPECT_CLIENT_HELLO -> State.SERVER_EXPECT_FINISHED
2021-04-29 18:28:10,019 DEBUG quic [0000000000000002] Discarding epoch Epoch.INITIAL
2021-04-29 18:28:10,020 DEBUG quic [0000000000000002] TLS State.SERVER_EXPECT_FINISHED -> State.SERVER_POST_HANDSHAKE
2021-04-29 18:28:10,021 DEBUG quic [0000000000000002] Discarding epoch Epoch.HANDSHAKE
2021-04-29 18:28:10,021 INFO quic [0000000000000002] ALPN negotiated protocol hq-29
2021-04-29 18:28:10,021 DEBUG quic [0000000000000002] Network path ('127.0.0.1', 4987) validated by handshake
2021-04-29 18:28:10,229 DEBUG quic [0000000000000002] Stream 8 created by peer
2021-04-29 18:28:10,230 INFO quic [0000000000000002] HTTP request GET /index.html
2021-04-29 18:28:10,735 DEBUG quic [0000000000000002] Loss detection triggered
2021-04-29 18:28:10,736 DEBUG quic [0000000000000002] Sending PING (probe) in packet 6
2021-04-29 18:28:10,748 DEBUG quic [0000000000000002] Network path ('127.0.0.1', 4988) discovered
2021-04-29 18:28:10,748 DEBUG quic [0000000000000002] Stream 4 created by peer
2021-04-29 18:28:10,748 DEBUG quic [0000000000000002] Stream 20 created by peer
2021-04-29 18:28:10,749 INFO quic [0000000000000002] Connection close code 0x1FD3, reason 
2021-04-29 18:28:10,749 DEBUG quic [0000000000000002] QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
2021-04-29 18:28:10,749 INFO quic [0000000000000002] HTTP request GET /index.html
2021-04-29 18:28:10,749 INFO quic [0000000000000002] HTTP request GET /index.html
2021-04-29 18:28:12,248 DEBUG quic [0000000000000002] Discarding epoch Epoch.ONE_RTT
2021-04-29 18:28:12,249 DEBUG quic [0000000000000002] QuicConnectionState.DRAINING -> QuicConnectionState.TERMINATED
2021-04-29 18:28:13,625 DEBUG quic [cc44abc349cff42c] Network path ('127.0.0.1', 4987) discovered
2021-04-29 18:28:13,627 DEBUG quic [cc44abc349cff42c] Payload decryption failed
2021-04-29 18:28:14,331 DEBUG quic [cc44abc349cff42c] Network path ('127.0.0.1', 4988) discovered
2021-04-29 18:28:14,331 ERROR asyncio Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/server.py", line 149, in datagram_received
    protocol.datagram_received(data, addr)
  File "/quic/aioquic/src/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/quic/aioquic/src/aioquic/quic/connection.py", line 793, in receive_datagram
    ), "first packet must be INITIAL"
AssertionError: first packet must be INITIAL
2021-04-29 18:28:15,799 DEBUG quic [cc44abc349cff42c] Payload decryption failed
