between random: 226535474
between random: 226535474
between random: 226535471
between random: 226535474
between random: 226535474
between random: 24119
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
timeout: the monitored command dumped core
Aborted
output directory: temp/2598
implementation directory: /home/chris/TVOQE_UPGRADE_27/quic/aioquic/
implementation command: python3 examples/http3_server.py --quic-log /home/chris/qlog_aiquic2 --certificate /home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_cert.pem --private-key /home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_key.pem  -v --host 127.0.0.1 --port 4443 -l /home/chris/secret.log
../quic_server_test_newcoid_length_error (0) ...
implementation command: ['python3', 'examples/http3_server.py', '--quic-log', '/home/chris/qlog_aiquic2', '--certificate', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_cert.pem', '--private-key', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_key.pem', '-v', '--host', '127.0.0.1', '--port', '4443', '-l', '/home/chris/secret.log']
quic_process pid: 18980
timeout 100 ./build/quic_server_test_newcoid_length_error seed=130 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
client return code: 134
FAIL
error: 1 tests(s) failed
